# 贊助連結配置
# 如需啟用 GitHub Sponsors，請取消下方註解並填入您的用戶名

# github: [your-username]
# patreon: your-patreon-username
# open_collective: your-open-collective-username
# ko_fi: your-ko-fi-username
# custom: ['https://your-custom-link.com']
